name: CI/CD with ArgoCD

on:
  push:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: heyanoop
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Images
      run: |
        declare -A service_repos=(
          [worker]="heyanoop/worker"
          [vote]="heyanoop/vote"
          [result]="heyanoop/result"
        )

        for service in "${!service_repos[@]}"; do
          repo=${service_repos[$service]}
          echo "Building and pushing image for $service to $repo..."
          docker build "./$service" --file "./$service/Dockerfile" --tag "$repo:${{ github.run_number }}"
          docker push "$repo:${{ github.run_number }}"
        done

    - name: Output Build Run Number
      run: echo "::set-output name=run_number::${{ github.run_number }}"
      id: build_output

  cd:
    needs: ci
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Update Kubernetes Manifests
      run: |
        declare -A service_repos=(
          [worker]="heyanoop/worker"
          [vote]="heyanoop/vote"
          [result]="heyanoop/result"
        )

        for service in "${!service_repos[@]}"; do
          repo=${service_repos[$service]}
          echo "Updating manifest for $service with image $repo:${{ github.run_number }}"
          sed -i "s|image: $repo:.*|image: $repo:${{ github.run_number }}|g" "k8s-specifications/${service}-deployment.yaml"
        done

    - name: Debug Updated Manifests
      run: cat k8s-specifications/*.yaml

    - name: Commit and Push Updated Manifests
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add k8s-specifications/*.yaml
        git commit -m "Update manifests with new image tags"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
